export enum LoanRequestStatus {
  REQUESTED= "REQUESTED",
  WAITING = "WAITING",
  APPROVED = "APPROVED",
  CANCELED = "CANCELED",
  APPROVEDBYUSER = "APPROVEDBYUSER",
  CANCELEDBYUSER = "CANCELEDBYUSER",
  FINISHED = "FINISHED"
}
